[build]
builder = "nixpacks"
buildCommand = "npm install && tsc -p tsconfig.json && vite build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
numRetries = 10

[deploy.envs]
NODE_ENV = "production"
